# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2023.7.22-hbcca054_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.38-h1181459_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran5-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/noarch/pybind11-abi-4-hd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-11.2.0-h00389a5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/c-ares-1.19.1-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/fmt-9.1.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/giflib-5.2.1-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/icu-73.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9e-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-3.0-h295c915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlicommon-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.17-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libev-4.33-h7f8727e_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libsodium-1.0.18-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-base-1.2.4-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-3.0.11-h7f8727e_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/reproc-14.2.4-h295c915_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.2-h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/linux-64/yaml-0.2.5-h7f98852_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/yaml-cpp-0.7.0-h295c915_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2023.1.0-hdb19cb5_46305.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlidec-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libbrotlienc-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libedit-3.1.20221030-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libnghttp2-1.52.0-h2d74bed_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.39-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.10.0-hdbd6064_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.10.4-hf1b16e4_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre2-10.42-hebb0a14_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/reproc-cpp-14.2.4-h295c915_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.12-h1ccaba5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.3.4-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.5.5-hc292b87_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-bin-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.12.1-h4a9f257_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.20.1-h143b758_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libarchive-3.6.2-h6ac8c49_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libsolv-0.7.24-he621ea3_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.5.1-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libxslt-1.1.37-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2023.1.0-h213fc3f_46343.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.41.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-1.0.9-h5eee18b_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.12-h3be6417_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-8.2.1-h251f7ec_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-1.2.4-h11a3e52_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.10.12-h955ad1f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/attrs-22.1.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/boltons-23.0.0-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/certifi-2023.7.22-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/click-8.0.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/colorama-0.4.6-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/debugpy-1.6.7-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/defusedxml-0.7.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/dill-0.3.7-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/entrypoints-0.4-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/et_xmlfile-1.1.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/exceptiongroup-1.0.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/greenlet-2.0.1-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/isort-5.9.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/joblib-1.2.0-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/json5-0.9.14-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jsonpointer-2.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.4.4-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lazy-object-proxy-1.6.0-py310h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libmamba-1.5.1-haf1ee3a_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lxml-4.9.2-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-2.1.1-py310h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/noarch/mccabe-0.7.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mdurl-0.1.0-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/mistune-3.0.1-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py310h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/noarch/munkres-1.1.4-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/natsort-8.4.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nest-asyncio-1.5.6-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-23.1-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/pandocfilters-1.5.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/linux-64/pillow-9.4.0-py310h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/platformdirs-3.10.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pluggy-1.0.0-py310h06a4308_1.conda
https://conda.anaconda.org/conda-forge/noarch/prometheus_client-0.18.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.9.0-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pycosat-0.6.4-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pygments-2.15.1-py310h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyparsing-3.0.9-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyrsistent-0.18.0-py310h7f8727e_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-fastjsonschema-2.16.2-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-json-logger-2.0.7-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-tzdata-2023.3-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.10-2_cp310.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2022.7-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-25.1.0-py310h6a678d5_0.conda
https://conda.anaconda.org/conda-forge/noarch/rfc3986-validator-0.1.1-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ruamel.yaml.clib-0.2.6-py310h5eee18b_1.conda
https://conda.anaconda.org/conda-forge/noarch/send2trash-1.8.2-pyh41d4057_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-67.8.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://conda.anaconda.org/conda-forge/noarch/sniffio-1.3.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/soupsieve-2.5-pyhd8ed1ab_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/tenacity-8.2.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.2.0-pyh0d69192_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tomli-2.0.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tomlkit-0.11.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/toolz-0.12.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.3.2-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tqdm-4.65.0-py310h2f386ee_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-5.7.1-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.7.1-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/typing_utils-0.1.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/webencodings-0.5.1-pyhd8ed1ab_2.conda
https://conda.anaconda.org/conda-forge/noarch/websocket-client-1.6.4-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.38.4-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wrapt-1.14.1-py310h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/xlrd-2.0.1-pyhd8ed1ab_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/zipp-3.17.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/anyio-4.0.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/async-lru-2.0.4-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/babel-2.13.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/beautifulsoup4-4.12.2-pyha770c72_0.conda
https://conda.anaconda.org/conda-forge/noarch/bleach-6.1.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.15.1-py310h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/importlib-metadata-6.8.0-pyha770c72_0.conda
https://conda.anaconda.org/conda-forge/noarch/importlib_resources-6.1.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.18.1-py310h06a4308_1.conda
https://conda.anaconda.org/conda-forge/noarch/jinja2-3.1.2-pyhd8ed1ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/jsonpatch-1.32-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jsonschema-4.17.3-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_core-5.3.0-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_pygments-0.2.2-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libmambapy-1.5.1-py310h2dafd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markdown-it-py-2.2.0-py310h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-inline-0.1.6-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/multipledispatch-0.6.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.26.0-py310hb5e798b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openpyxl-3.0.10-py310h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/overrides-7.4.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-23.1.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/plotly-5.9.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/prompt-toolkit-3.0.36-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-6.0-py310h5764c6d_4.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/rfc3339-validator-0.1.4-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ruamel.yaml-0.17.21-py310h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/terminado-0.17.1-pyh41d4057_0.conda
https://conda.anaconda.org/conda-forge/noarch/tinycss2-1.2.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/typing-extensions-4.7.1-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/argon2-cffi-bindings-21.2.0-py310h5764c6d_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/astroid-2.14.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py310h7f8727e_1002.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-39.0.1-py310h9ce1e76_2.conda
https://conda.anaconda.org/conda-forge/noarch/importlib_metadata-6.8.0-hd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_client-8.1.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_events-0.6.3-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyter_server_terminals-0.4.4-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/nbformat-5.9.2-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pydantic-1.10.12-py310h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/rich-13.3.5-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlalchemy-2.0.21-py310h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zstandard-0.19.0-py310h5eee18b_0.conda
https://conda.anaconda.org/conda-forge/noarch/argon2-cffi-23.1.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/conda-content-trust-0.1.3-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/conda-package-streaming-0.9.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython-8.15.0-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/nbclient-0.8.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pylint-2.16.2-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-23.2.0-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/conda-package-handling-2.2.0-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/ipykernel-6.15.0-pyh210e3f2_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbconvert-core-7.10.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.16-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyter_server-2.9.1-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.31.0-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyter-lsp-2.2.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyterlab_server-2.22.0-py310h06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/notebook-shim-0.2.3-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyterlab-4.0.7-pyhd8ed1ab_0.conda
https://conda.anaconda.org/bioconda/noarch/psims-1.2.8-pyhdfd78af_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/scienceplots-2.1.0-pyhd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/bottleneck-1.3.5-py310ha9d4c09_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/contourpy-1.0.5-py310hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.7.2-py310h1128e8f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.6-py310h1128e8f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.2-py310h1128e8f_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.26.0-py310h5f9d8c6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numexpr-2.8.4-py310h85018f9_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/patsy-0.5.3-py310h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.11.1-py310h5f9d8c6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pandas-1.5.3-py310h1128e8f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/scikit-learn-1.3.0-py310h1128e8f_0.conda
https://conda.anaconda.org/bioconda/noarch/pyteomics-4.6.2-pyh7cba7a3_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/statsmodels-0.14.0-py310ha9d4c09_0.conda
https://conda.anaconda.org/conda-forge/noarch/xarray-2023.5.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/pandas_flavor-0.6.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/bioconda/noarch/psm-utils-0.5.0-pyhdfd78af_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/seaborn-0.10.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyjanitor-0.23.1-pyhd8ed1ab_1.conda
https://conda.anaconda.org/conda-forge/noarch/statannotations-0.5.0-pyhd8ed1ab_0.tar.bz2
