from setuptools import setup, find_packages

setup(
    name="SWAPS",
    version="0.1.0",
    description="Scan-Wise Activation and Peak Selection",
    url="https://github.com/wilhelm-lab/SWAPS",
    author="Zixuan Xiao",
    author_email="zixuan.xiao@tum.de",
    license="MIT license",
    packages=find_packages(),
    install_requires=[
        "alphabase==1.3.0",
        "alphatims==1.0.8",
        "Bio==1.7.1",
        "biopython==1.83",
        "directlfq==0.2.19",
        "docopt==0.6.2",
        "fire==0.5.0",
        "h5py==3.10.0",
        "IsoSpecPy==2.2.2",
        "joblib==1.3.2",
        "matplotlib==3.7.2",
        "matplotlib_venn==0.11.9",
        "numpy==1.25.0",
        "pandas==2.2.3",
        "peptdeep==1.2.1",
        "plotly==5.9.0",
        "pyjanitor==0.23.1",
        "pyteomics==4.6.2",
        "python-dotenv==1.0.1",
        "scikit_learn==1.3.0",
        "scipy==1.15.1",
        "seaborn==0.13.2",
        "sparse==0.15.1",
        "statsmodels==0.14.0",
        "torch==2.3.0",
        "torcheval==0.0.7",
        "torchvision==0.18.0",
        "tensorboard==2.12.3",
        "tqdm==4.66.5",
        "yacs==0.1.8",
    ],
    # entry_points={
    #     "console_scripts": [
    #         # Add any command line scripts here
    #     ],
    # },
    classifiers=[
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
)
