DESCRIPTION: "Prepare data for pasef ecoli 120min"

PREPARE_DATASET:
  ENABLE: true
  INPUT:
    TIMS_DATA_PATH: /cmnfs/proj/ORIGINS/data/species_mix/library/20240902_Ecolit_15ug_120min_R1_1_1_5881.d/
    OK_OUTPUT_DIR: null
    MQ_001_DIR: /cmnfs/proj/ORIGINS/data/species_mix/library/txt_ecoli_120min/
    MQ_100_DIR: null
  N_DIGITS: 3
  N_BATCH: 32
  OUT_FILE_DIR: /cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/data_exploration/precursor_fit_pasef_ecoli_120min_10r_update_wd/
  CALCULATE_PRECURSOR_METRICS: true
  PREPARE_TORCH_DATASET: false
  
MODEL:
  KEEP_TRAINING: false