DESCRIPTION: "Experiment with TCN"

PREPARE_DATASET:
  ENABLE: false
  INPUT:
    TIMS_DATA_PATH: /cmnfs/proj/ORIGINS/data/random_precursor_sampling/nanoflow_bruker/PASEF_6ramps_200ng_K562_15min_Slot2-2_1_6931.d/
    OK_OUTPUT_DIR: /cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/rescoring/out_no_rl_fix_ce_mokapot_pasef/
    MQ_001_DIR: /cmnfs/proj/ORIGINS/data/random_precursor_sampling/nanoflow_bruker/txt_001FDR_15min_60min/
    MQ_100_DIR: /cmnfs/proj/ORIGINS/data/random_precursor_sampling/nanoflow_bruker/txt_100FDR_15min
  N_DIGITS: 3
  N_BATCH: 5
  OUT_FILE_DIR: /cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/

MODEL:
  KEEP_TRAINING: true
  TYPE: precursor_classification
  NAME: ResNet1D
  EXP_DIR: '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/exp_ResNet1D_depth2_undersample'
  RESUME_PATH: ""
  PARAMS:
    NUM_CLASSES: 2
    RESNET:
      DEPTH: 2
      INITIAL_CHANNEL: 32
      DROPOUT_RATE: 0.5
  DATASET: 
    TRAINING_DATA: 
    - '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_3ramps_200ng_K562_15min_Slot2-2_1_6933_4.pkl'
    - '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_3ramps_200ng_K562_15min_Slot2-2_1_6933_3.pkl'
    - '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_3ramps_200ng_K562_15min_Slot2-2_1_6933_2.pkl'
    - '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_3ramps_200ng_K562_15min_Slot2-2_1_6933_1.pkl'
    - '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_3ramps_200ng_K562_15min_Slot2-2_1_6933_0.pkl'
    - '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_6ramps_200ng_K562_15min_Slot2-2_1_6931_2.pkl'
    - '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_6ramps_200ng_K562_15min_Slot2-2_1_6931_1.pkl'
    - '/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_6ramps_200ng_K562_15min_Slot2-2_1_6931_4.pkl'
    VALIDATION_DATA: ['/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_6ramps_200ng_K562_15min_Slot2-2_1_6931_3.pkl']
    TEST_DATA: ['/cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/data_dict_PASEF_6ramps_200ng_K562_15min_Slot2-2_1_6931_0.pkl']
    SAMPLING_STRATEGY: undersample
    TRAINING_BATCH_SIZE: 2048
    VALIDATION_BATCH_SIZE: 4096
    TEST_BATCH_SIZE: 4096
  SOLVER:
    TOTAL_EPOCHS: 100
    LOSS:
      NAME: BCEWithLogitsLoss
      POS_WEIGHT: [1, 1]
      ALPHA: 0.25
      GAMMA: 2
    EARLY_STOPPING:
      PATIENCE: 10
      MODE: "min"
      MONITOR: "val_loss"
