DESCRIPTION: "Prepare data for pasef"

PREPARE_DATASET:
  ENABLE: true
  INPUT:
    TIMS_DATA_PATH: /cmnfs/proj/ORIGINS/data/random_precursor_sampling/nanoflow_bruker/PASEF_1ramps_200ng_K562_15min_Slot2-2_1_6935.d/
    OK_OUTPUT_DIR: /cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/rescoring/out_no_rl_fix_ce_mokapot_pasef/
    MQ_001_DIR: /cmnfs/proj/ORIGINS/data/random_precursor_sampling/nanoflow_bruker/txt_001FDR_15min_60min/
    MQ_100_DIR: /cmnfs/proj/ORIGINS/data/random_precursor_sampling/nanoflow_bruker/txt_100FDR_15min
  N_DIGITS: 3
  N_BATCH: 5
  OUT_FILE_DIR: /cmnfs/proj/ORIGINS/SWAPS_precursor_sampling/bruker_nanoflow/predict_identifiability/data/pasef_15min_1r/

MODEL:
  KEEP_TRAINING: false
