RESULT_PATH: /cmnfs/proj/ORIGINS/SWAPS_exp/tims_ramp_time/100ms_exp_library_no_decoy
ADD_TIMESTAMP_TO_RESULT_PATH: true
DATA_PATH: /cmnfs/proj/ORIGINS/data/tims_ramp_time/Hela2ug_lowflow_30min_1to37to42_NCE29to59_100ms7R_RA2_1_2078.d/
DEBUG: false
DICT_PICKLE_PATH: ''
EXPORT_DATA_HDF5_DIR: ''
MQ_REF_PATH: /cmnfs/proj/ORIGINS/data/tims_ramp_time/combined_30min_gradient/txt/evidence_100ms.txt
MQ_EXP_PATH: /cmnfs/proj/ORIGINS/data/tims_ramp_time/combined_30min_gradient/txt/evidence.txt
FILTER_EXP_BY_RAW_FILE: []
N_CPU: 10
OPTIMIZATION:
  N_BLOCKS_BY_PEPT: 1
  N_BATCH: 10
PREPARE_DICT:
  DICT_PICKLE_PATH: ''
  FILTER_PRED_BY_RAW_FILE: ''
  FILTER_TRAIN_BY_RAW_FILE: ''
  GENERATE_DECOY: false
  IM_REF: exp
  RT_REF: exp
  RT_TOL: 0.001
RANDOM_SEED: 42
PEAK_SELECTION:
  ENABLE: false
RESULT_ANALYSIS:
  ENABLE: true
  POST_PROCESSING:
    FILTER_BY_IM: true
