RESULT_PATH: /cmnfs/proj/ORIGINS/SWAPS_exp/short_gradient/30min_3to45_7R_30min_exp_library_no_decoy_MBR_R3
ADD_TIMESTAMP_TO_RESULT_PATH: true
DATA_PATH: /cmnfs/proj/ORIGINS/data/HeLa_sample_amount_and_LC_columns/30min_5ug_ref/Hela_30min_5ug_R3_RA1_1_5164.d/
DEBUG: false
DICT_PICKLE_PATH: ''
EXPORT_DATA_HDF5_DIR: ''
MQ_REF_PATH: /cmnfs/proj/ORIGINS/data/HeLa_sample_amount_and_LC_columns/30min_5ug_ref/txt_30min_5ug/evidence.txt
MQ_EXP_PATH: /cmnfs/proj/ORIGINS/data/HeLa_sample_amount_and_LC_columns/30min_5ug_ref/txt_30min_5ug/evidence.txt
FILTER_EXP_BY_RAW_FILE: []
N_CPU: 10
OPTIMIZATION:
  N_BLOCKS_BY_PEPT: 1
  N_BATCH: 10
PREPARE_DICT:
  DICT_PICKLE_PATH: ''
  FILTER_PRED_BY_RAW_FILE: ''
  FILTER_TRAIN_BY_RAW_FILE: ''
  KEEP_MATCHED_PRECURSORS: false
  GENERATE_DECOY: false
  IM_REF: ref
  RT_REF: ref
  RT_TOL: 0.2 # Use 0.2 as half of MaxQuant MBR default
RANDOM_SEED: 42
PEAK_SELECTION:
  ENABLE: false
RESULT_ANALYSIS:
  ENABLE: true
  POST_PROCESSING:
    FILTER_BY_IM: true
