DATA_PATH: '/cmnfs/proj/ORIGINS/data/tims_ramp_time/Hela2ug_lowflow_30min_1to37to42_NCE29to59_100ms7R_RA2_1_2078.d/'
RESULT_PATH: '/cmnfs/proj/ORIGINS/SWAPS_exp/tims_ramp_time/corrected_RT_tol_pred_120min_library_100ms'
ADD_TIMESTAMP_TO_RESULT_PATH: True
MQ_REF_PATH: ''
EXPORT_DATA_HDF5_DIR: ""
PREPARE_DICT:
  FILTER_TRAIN_BY_RAW_FILE: ""
  FILTER_PRED_BY_RAW_FILE: None
  MZ_BIN_DIGITS: 2
  RT_REF: 'pred'
  RT_TOL: -1.0
  RT_PRED:
    TRAIN_DATA: '/cmnfs/proj/ORIGINS/data/tims_ramp_time/combined/txt/evidence.txt'
    PREDICT_DATA: '/cmnfs/proj/ORIGINS/data/tims_ramp_time/HeLa_library/txt_Hela_DDA_120min/evidence.txt' # empty string to use train data for prediction
DICT_PICKLE_PATH: ''
OPTIMIZATION:
  # RT_TOL: 0.0
  N_CPU: 5
  N_BATCH: 5
  N_BLOCKS_BY_PEPT: 2
  MZ_BIN_DIGITS: 2
  # RT_REF: 'exp'
RESULT_ANALYSIS:
  ENABLE: true
  FILTER_BY_RAW_FILE: ''
  FILTER_BY_RT_OVERLAP:
  - full_overlap
  MQ_EXP_PATH: '/cmnfs/proj/ORIGINS/data/tims_ramp_time/combined/txt/evidence.txt'
  POST_PROCESSING:
    FILTER_BY_IM: false

