DATA_PATH: '/cmnfs/proj/ORIGINS/data/species_mix/DDA/MixA_5ug_30min_7R_R3_RA1_1_5137.d/'
RESULT_PATH: '/cmnfs/proj/ORIGINS/SWAPS_exp/mixture/MixA_5ug_30min_7R_R3_RA1_1_5137'
ADD_TIMESTAMP_TO_RESULT_PATH: True
MQ_REF_PATH: ''
EXPORT_DATA_HDF5_DIR: ""
PREPARE_DICT:
  RAW_FILE: ""
  MZ_BIN_DIGITS: 2
  RT_REF: 'exp'
  RT_TOL: 0.0
  RT_PRED:
    TRAIN_DATA: '/cmnfs/proj/ORIGINS/data/species_mix/DDA/txt_HYE_5ug/evidence.txt'
    PREDICT_DATA: '' # empty string to use train data for prediction
DICT_PICKLE_PATH: ''
OPTIMIZATION:
  RT_TOL: 0.0
  N_CPU: 5
  N_BATCH: 5
  N_BLOCKS_BY_PEPT: 1
  MZ_BIN_DIGITS: 2
  RT_REF: 'exp'
RESULT_ANALYSIS:
  ENABLE: True
  MQ_EXP_PATH: ""
  POST_PROCESSING:
    FILTER_BY_IM: True

