# relevant columns in exp
exp_cols = [
    "Sequence",
    "Modified sequence",
    "Charge",
    "Intensity",
    "Type",
    "Raw file",
    "Retention time",
    "Calibrated retention time",
    "Retention length",
    "Calibrated retention time start",
    "Calibrated retention time finish",
    "Ion mobility length",
    "1/K0",
    "1/K0 length",
    "Calibrated 1/K0",
    "Reverse",
    "MS/MS scan number",
    "Proteins",
    "m/z",
    "PEP",
    "Score",
]
decoy_mutation_rule = {
    "G": "L",
    "A": "L",
    "V": "L",
    "L": "V",
    "I": "V",
    "F": "L",
    "M": "L",
    "P": "L",
    "W": "L",
    "S": "T",
    "C": "S",
    "T": "S",
    "Y": "S",
    "H": "S",
    "K": "L",
    "R": "L",
    "Q": "N",
    "E": "D",
    "N": "Q",
    "D": "E",
}
