from yacs.config import CfgNode as ConfigurationNode

__C = ConfigurationNode()

# importing default as a global singleton
train_cfg = __C

# general setup
__C.DESCRIPTION = "Default config from the Singleton"

__C.PREPARE_DATASET = ConfigurationNode()

__C.PREPARE_DATASET.ENABLE = True

__C.PREPARE_DATASET.INPUT = ConfigurationNode()
__C.PREPARE_DATASET.INPUT.TIMS_DATA_PATH = ""
__C.PREPARE_DATASET.INPUT.OK_OUTPUT_DIR = ""
__C.PREPARE_DATASET.INPUT.MQ_001_DIR = ""
__C.PREPARE_DATASET.INPUT.MQ_100_DIR = ""

__C.PREPARE_DATASET.N_DIGITS = 3
__C.PREPARE_DATASET.N_BATCH = 5
__C.PREPARE_DATASET.OUT_FILE_DIR = ""


__C.MODEL = ConfigurationNode()
__C.MODEL.KEEP_TRAINING = True
__C.MODEL.TYPE = "precursor_classification"
__C.MODEL.NAME = "TCN"

__C.MODEL.PARAMS = ConfigurationNode()
__C.MODEL.PARAMS.NUM_CLASSES = 2
__C.MODEL.TRAINING_DATA = []
__C.MODEL.VALIDATION_DATA = []
__C.MODEL.TEST_DATA = []
__C.MODEL.TRAINING_BATCH_SIZE = 1024
__C.MODEL.VALIDATION_BATCH_SIZE = 1024
__C.MODEL.TEST_BATCH_SIZE = 1024
__C.MODEL.MAX_LEN = 3002
__C.MODEL.EXP_DIR = ""
__C.MODEL.ADD_TIMESTAMP_TO_RESULT_PATH = True
__C.MODEL.RESUME_PATH = ""
### solver
__C.MODEL.SOLVER = ConfigurationNode()
__C.MODEL.SOLVER.TOTAL_EPOCHS = 100

#### optimizer
__C.MODEL.SOLVER.OPTIMIZER = ConfigurationNode()
__C.MODEL.SOLVER.OPTIMIZER.BASE_LR = 0.001
__C.MODEL.SOLVER.OPTIMIZER.NAME = "adam"
__C.MODEL.SOLVER.OPTIMIZER.WEIGHT_DECAY = 0

#### sgd config
__C.MODEL.SOLVER.OPTIMIZER.SGD = ConfigurationNode()
__C.MODEL.SOLVER.OPTIMIZER.SGD.MOMENTUM = 0.9
__C.MODEL.SOLVER.OPTIMIZER.SGD.NESTEROV = False

#### LR scheduler config
__C.MODEL.SOLVER.SCHEDULER = ConfigurationNode()
__C.MODEL.SOLVER.SCHEDULER.NAME = "one_cycle"
__C.MODEL.SOLVER.SCHEDULER.PATIENCE = 3
__C.MODEL.SOLVER.SCHEDULER.MIN_LR = 0.00000001
__C.MODEL.SOLVER.SCHEDULER.LR_REDUCE_GAMMA = 0.1
__C.MODEL.SOLVER.SCHEDULER.FACTOR = 0.1

##### OneCycleLR hyperparams
__C.MODEL.SOLVER.SCHEDULER.PCT_START = 0.3
__C.MODEL.SOLVER.SCHEDULER.ANNEAL_STRATEGY = "cos"
__C.MODEL.SOLVER.SCHEDULER.DIV_FACTOR = 25
__C.MODEL.SOLVER.SCHEDULER.MAX_LR = 0.01

#### Loss
__C.MODEL.SOLVER.LOSS = ConfigurationNode()
__C.MODEL.SOLVER.LOSS.NAME = "BCEWithLogitsLoss"
__C.MODEL.SOLVER.LOSS.POS_WEIGHT = [1, 4]
__C.MODEL.SOLVER.LOSS.ALPHA = 0.25
__C.MODEL.SOLVER.LOSS.GAMMA = 2

#### Early Stopper
__C.MODEL.SOLVER.EARLY_STOPPING = ConfigurationNode()
__C.MODEL.SOLVER.EARLY_STOPPING.PATIENCE = 10
__C.MODEL.SOLVER.EARLY_STOPPING.MODE = "max"
__C.MODEL.SOLVER.EARLY_STOPPING.MONITOR = "val_ap"
