CONFMODEL:
  DATASET_RESPLIT: True
  BINARY_LABEL: True
  PARAMS:
    FIRST_OUT_CHANNELS: 32
    DROPOUT_RATE: 0.25
    DOWNHILL: 5
    SIGMOID_OUTPUT: True
  SOLVER:
    TOTAL_EPOCHS: 100
    EARLY_STOPPING:
      PATIENCE: 10
      MODE: max
    OPTIMIZER:
      WEIGHT_DECAY: 0.0
    LOSS:
      NAME: BCELoss
  EVAL:
    METRIC: ROCAUC
  
