CONFMODEL:
  DATASET_RESPLIT: True
  PARAMS:
    FIRST_OUT_CHANNELS: 32
    DROPOUT_RATE: 0.0
    DOWNHILL: 5
  SOLVER:
    TOTAL_EPOCHS: 100
    EARLY_STOPPING:
      PATIENCE: 15
    OPTIMIZER:
      WEIGHT_DECAY: 0.0
  
